### ISSUE TITLE
Vorschläge & Ideen:

### ISSUE THREAD

**Issue by fellmoon** [schiederme/tinyhouse#1]
Anregungen:
- Nessa goes Wild, die hat ein Tiny House gebaut und spricht da relativ transparent auch über kosten & teilweise Probleme etc. https://www.youtube.com/channel/UCV7liswUxCOLqV73zUthXow

- Der Bauhaus Campus in Berlin hat im Kontext experimenteller Architektur da ein paar TinyHouse-Konzepte stehen bzw. im werden, u.a. auch einen mit ner Wechselbrücke, wenn ich mich richtig erinnere... evt. da mal vorbeischauen oder anfragen.
bauhauscampus.org/tiny-houses/ 

Was man braucht:
- Dämmung(!!!)
- WC > Trockentrenntoilette evt. eine Option? Einfacher umzusetzen und reduziert den Wasserverbrauch

Wie ist die Rechtslage mit dem Ding irgendwo zu stehen in HH?

**Comment by schiederme** [comment]
Danke für deinen Issue!

Dämmung ist natürlich wichtig und wird natürlich eingebaut.
Toiletten überlegen wir noch.

Zu der Rechtslage müssen wir noch ein wenig Lesen und uns einarbeiten.

Grüße,
Maxi

**Comment by schiederme** [comment]
Aloha,
es geht weiter.

Dämmung: Hanf oder Jute

WC: Kompostoilette wäre das beste, wie du bereits sagtest. Also wird es vermutlich auch eine.

Dusche: Ist auch wichtig. Da müsste man überlegen, ob man einen Mini Durchlauferhitzer nimmt oder einen 40l boiler.

**Comment by schiederme** [comment]
Ok, es gab viele Überlegungen in letzter zeit. Wir haben jetzt ein Konzept für den Bau des Hauses und einen Zimmerer Meister der uns bei der Umsetzung helfen wird. Es wird anderst als geplant kein einfach transportables TinyHouse sein. Zumindest die Version 1.

Wir haben dafür ein Grundstück was wir nutzen dürfen. Die Selbstbaukosten werden bei ca. 15k€ liegen und das Haus ist mit einem Kranen versetzbar. Sprich es ist einfach umzusetzen, wenn man auch einen Kranen und Tieflader braucht.

**Comment by schiederme** [comment]
Update :P 

Komposttoilette? -> Jip
Portable -> Jip
Preis -> um die 7500€
Bauanleitung/Bauplan ist im kopf schon fertig.
